let handler = m => m

handler.before = function (m) {
  let user = global.DATABASE.data.users[m.sender]
        let role = (user.level <= 2) ? 'Warrior ll ✯'
          : ((user.level >= 2) && (user.level <= 4)) ? 'Warrior ll ✯✯'
          : ((user.level >= 4) && (user.level <= 6)) ? 'Warrior ll ✯✯✯'
          : ((user.level >= 6) && (user.level <= 8)) ? 'Warrior l ✯'
          : ((user.level >= 8) && (user.level <= 10)) ? 'Warrior l ✯✯'
          : ((user.level >= 10) && (user.level <= 20)) ? 'Warrior l ✯✯✯'
          : ((user.level >= 20) && (user.level <= 30)) ? 'Elite lll ✯'
          : ((user.level >= 30) && (user.level <= 40)) ? 'Elite lll ✯✯'
          : ((user.level >= 40) && (user.level <= 50)) ? 'Elite lll ✯✯✯'
          : ((user.level >= 50) && (user.level <= 60)) ? 'Elite ll ✯'
          : ((user.level >= 60) && (user.level <= 70)) ? 'Elite ll ✯✯' 
          : ((user.level >= 70) && (user.level <= 80)) ? 'Elite ll ✯✯✯' 
          : ((user.level >= 80) && (user.level <= 90)) ? 'Elite l ✯' 
          : ((user.level >= 90) && (user.level <= 100)) ? 'Elite l ✯✯' 
          : ((user.level >= 100) && (user.level <= 110)) ? 'Elite l ✯✯✯ '
          : ((user.level >= 110) && (user.level <= 120)) ? 'Master lll ✯'
          : ((user.level >= 120) && (user.level <= 130)) ? 'Master lll ✯✯'
          : ((user.level >= 130) && (user.level <= 140)) ? 'Master lll ✯✯✯'
          : ((user.level >= 140) && (user.level <= 150)) ? 'Master ll ✯'
          : ((user.level >= 150) && (user.level <= 160)) ? 'Master ll ✯✯' 
          : ((user.level >= 160) && (user.level <= 170)) ? 'Master ll ✯✯✯' 
          : ((user.level >= 170) && (user.level <= 180)) ? 'Master l ✯' 
          : ((user.level >= 180) && (user.level <= 190)) ? 'Master l ✯✯' 
          : ((user.level >= 190) && (user.level <= 200)) ? 'Master l ✯✯✯' 
          : ((user.level >= 200) && (user.level <= 210)) ? 'GrandMaster lll ✯' 
          : ((user.level >= 210) && (user.level <= 220)) ? 'GrandMaster lll ✯✯'
          : ((user.level >= 220) && (user.level <= 230)) ? 'GrandMaster lll ✯✯✯'
          : ((user.level >= 230) && (user.level <= 240)) ? 'GrandMaster ll ✯'
          : ((user.level >= 240) && (user.level <= 250)) ? 'GrandMaster ll ✯✯'
          : ((user.level >= 250) && (user.level <= 260)) ? 'GrandMaster ll ✯✯✯'
          : ((user.level >= 260) && (user.level <= 270)) ? 'GrandMaster l ✯'
          : ((user.level >= 270) && (user.level <= 280)) ? 'GrandMaster l ✯✯'  
          : ((user.level >= 280) && (user.level <= 290)) ? 'GrandMaster l ✯✯✯' 
          : ((user.level >= 290) && (user.level <= 300)) ? 'Epic lll ✯' 
          : ((user.level >= 300) && (user.level <= 310)) ? 'Epic lll ✯✯'
          : ((user.level >= 310) && (user.level <= 320)) ? 'Epic lll ✯✯✯'
          : ((user.level >= 320) && (user.level <= 330)) ? 'Epic ll ✯'
          : ((user.level >= 330) && (user.level <= 340)) ? 'Epic ll ✯✯'
          : ((user.level >= 340) && (user.level <= 350)) ? 'Epic ll ✯✯✯'
          : ((user.level >= 350) && (user.level <= 360)) ? 'Epic l ✯'
          : ((user.level >= 360) && (user.level <= 370)) ? 'Epic l ✯✯'
          : ((user.level >= 370) && (user.level <= 380)) ? 'Epic l ✯✯✯'
          : ((user.level >= 380) && (user.level <= 390)) ? 'Legend lll ✯'
          : ((user.level >= 390) && (user.level <= 400)) ? 'Legend lll ✯✯'
          : ((user.level >= 400) && (user.level <= 410)) ? 'Legend lll ✯✯✯'
          : ((user.level >= 410) && (user.level <= 420)) ? 'Legend ll ✯'
          : ((user.level >= 420) && (user.level <= 430)) ? 'Legend ll ✯✯'
          : ((user.level >= 430) && (user.level <= 440)) ? 'Legend ll ✯✯✯'
          : ((user.level >= 440) && (user.level <= 450)) ? 'Legend l ✯'
          : ((user.level >= 450) && (user.level <= 460)) ? 'Legend l ✯✯'
          : ((user.level >= 460) && (user.level <= 470)) ? 'Legend l ✯✯✯'
          : ((user.level >= 470) && (user.level <= 480)) ? 'Mythic lll ✯'
          : ((user.level >= 480) && (user.level <= 490)) ? 'Myyhic lll ✯✯' 
          : ((user.level >= 490) && (user.level <= 500)) ? 'Mythic lll ✯✯✯'
          : ((user.level >= 500) && (user.level <= 600)) ? 'Mythic ll ✯'
          : ((user.level >= 600) && (user.level <= 700)) ? 'Mythic ll ✯✯'
          : ((user.level >= 700) && (user.level <= 800)) ? 'Mythic ll ✯✯✯ '
          : ((user.level >= 800) && (user.level <= 900)) ? 'Mythic l ✯✯'
          : ((user.level >= 900) && (user.level <= 1000)) ? 'Mythic l ✯✯✯'
          : 'Glorious Mythic ✪'
  user.role = role
  return true
}

module.exports = handler
